name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-wally:
    name: "Publish to Wally"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> "$GITHUB_PATH"
        shell: bash

      - name: Install Tools
        run: |
          rokit install --no-trust-check
        shell: bash

      - name: Login
        run: |
          wally login --token ${{ secrets.WALLY_TOKEN }}
        shell: bash

      - name: Publish
        run: |
          wally publish
        shell: bash

  publish-demo-place:
    name: "Publish Roblox Demo Place"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> "$GITHUB_PATH"
        shell: bash

      - name: Install Tools
        run: |
          rokit install --no-trust-check
        shell: bash

      - name: Build place file
        run: |
          rojo build -o Iris.rbxl ./demo.project.json
        shell: bash

      - name: Publish
        run: |
          rbxcloud experience publish -a ${{ secrets.PLACE_KEY }} -u 2823622397 -i 7245022703 -t published -f Iris.rbxl
        shell: bash
