name: Release

on:
  push:
    tags: ["v*"]

jobs:
  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} --draft --verify-tag --title ${{ github.ref_name }} --notes ${{ github.ref_name }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-files:
    needs: ["create-release"]
    name: "Build files"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> "$GITHUB_PATH"
        shell: bash

      - name: Install Tools
        run: |
          rokit install --no-trust-check
        shell: bash

      - name: Build files
        run: |
          rojo build -o Iris.rbxm ./default.project.json
          rojo build -o Iris.rbxl ./demo.project.json
          zip -r Iris.zip lib
        shell: bash

      - name: Upload files
        run: |
          gh release upload ${{ github.ref_name }} ./Iris.rbxm ./Iris.rbxl ./Iris.zip
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
